/**
 * Data Source Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The repository information is injected during the CI/CD build process
 * to enable fetching data from the data branch
 */

const DATA_CONFIG = {
    /**
     * GitHub repository owner (username)
     * This will be replaced during GitHub Actions workflow execution
     */
    repoOwner: 'gongchuyao',

    /**
     * GitHub repository name
     * This will be replaced during GitHub Actions workflow execution
     */
    repoName: 'daily-arXiv-ai-enhanced',

    /**
     * Data branch name
     * Default: 'data'
     */
    dataBranch: 'data',

    /**
     * Cache version - bump to force CDN cache refresh
     */
    dataVersion: '3',

    /**
     * Get the base URL for raw GitHub content from data branch
     * Uses jsDelivr CDN for better global accessibility (including China)
     * @returns {string} Base URL for data branch content
     */
    getDataBaseUrl: function() {
        return `https://cdn.jsdelivr.net/gh/${this.repoOwner}/${this.repoName}@${this.dataBranch}`;
    },

    /**
     * Get the full URL for a data file
     * @param {string} filePath - Relative path to the data file (e.g., 'data/2025-01-01.jsonl')
     * @returns {string} Full URL to the data file
     */
    getDataUrl: function(filePath) {
        return `${this.getDataBaseUrl()}/${filePath}`;
    }
};
